# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

#encoding: "UTF-8"

# css_inline: true

# Site settings
url: 'https://tech.allwithinspace.com'
baseurl: ''
encoding: "UTF-8" # Make sure the encoding is right
title: 'Allwithinspace'
description: 'Blog site on Technology & Distributed Computing'
#permalink: pretty
logo: "/assets/logo4.png"

sass:
  style: compressed
  sass_dir: _sass

# Pagination
paginate: 8
paginate_path: blog/page:num

sass:
  style: compressed # Style compression
permalink: /:categories/:title/  # define url construction

# default markdown processor and highlighter
markdown: kramdown
highlighter: rouge
error_mode: strict

# Social
author: Prasanna Raman Sridhar # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Prasanna Raman Sridhar # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/sp_raman
    - https://www.linkedin.com/in/sprasannaraman
    - https://github.com/allwithinspace

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/

defaults:
  - scope:
      path: ""
      type: tag
    values:
      layout: tag

# Footer nav
navigation_footer:
- title: 'Tech Blog'
  url: ""

# Contact
contact:
  linkedin:   https://www.linkedin.com/in/sprasannaraman
  github:     https://github.com/allwithinspace
  twitter:    https://twitter.com/sp_raman

# Collections
collections:
  posts:
    title: Blog Posts
    output: true
    description:
    feature_text: |
      <h2 style="color:white">Infinite Thoughts</h2>
    feature_image: "https://picsum.photos/2560/600?image=294"
  tag:
      output: true
